INSERT INTO `message` (`id`, `language`, `translation`) VALUES
(1, 'ar', 'تسجيل الدخول'),
(1, 'en', 'Login'),
(2, 'ar', 'تسجيل حساب جديد'),
(2, 'en', 'Sign up'),
(3, 'ar', 'معلومات عنا'),
(3, 'en', 'ِAbout Us'),
(4, 'ar', 'تسجيل الخروج'),
(4, 'en', 'Logout'),
(5, 'ar', 'تواصل معنا'),
(5, 'en', 'Contact Us'),
(6, 'ar', 'اسم المستخدم'),
(6, 'en', 'Username'),
(7, 'ar', 'الرقم السري'),
(7, 'en', 'Password'),
(8, 'ar', 'تذكرني'),
(8, 'en', 'Remember me'),
(9, 'ar', 'رقم الهاتف'),
(9, 'en', 'Phone Number'),
(10, 'ar', 'نسيت الرقم السري ؟'),
(10, 'en', 'Forgot your password ?'),
(11, 'ar', 'أرسال رسالة تفعيل جديد ؟'),
(11, 'en', 'Need new verification ?'),
(12, 'ar', 'تسجيل الدخول بستخدام الفيسبوك'),
(12, 'en', 'Login with facebook'),
(13, 'ar', 'إعادة تعيين'),
(13, 'en', 'Reset'),
(14, 'ar', 'إعادة الارسال'),
(14, 'en', 'Resend'),
(15, 'ar', 'وقد تم بالفعل اتخاذ هذا المستخدم.'),
(15, 'en', 'This username has already been taken.'),
(16, 'ar', 'تم أخذ عنوان البريد الإلكتروني هذا بالفعل.'),
(16, 'en', 'This email address has already been taken.'),
(17, 'ar', 'إذا كانت لديك استفسارات تجارية أو أسئلة أخرى ، فيرجى ملء النموذج التالي للاتصال بنا. شكرا لك.'),
(17, 'en', 'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.'),
(18, 'ar', 'حفظ'),
(18, 'en', 'Submit'),
(19, 'ar', 'الاسم'),
(19, 'en', 'Name'),
(20, 'ar', 'الموضوع'),
(20, 'en', 'Subject'),
(21, 'ar', 'المحتوى'),
(21, 'en', 'Body'),
(22, 'ar', 'البريد الاكتروني'),
(22, 'en', 'Email'),
(23, 'ar', 'لا يمكن أن تكون {attribute} فارغة.'),
(23, 'en', '{attribute} cannot be blank.'),
(28, 'ar', 'اسم المستخدم'),
(28, 'en', 'Username'),
(29, 'ar', 'لا يمكن أن تكون {attribute} فارغة.'),
(29, 'en', '{attribute} cannot be blank.'),
(31, 'ar', 'رقم الهاتف هذا مستخدم بالفعل'),
(31, 'en', 'This phone number has already been taken.'),
(32, 'ar', 'رقم الهاتف أو كلمة المرور غير صحيحة.'),
(32, 'en', 'Incorrect phone number or password.'),
(33, 'ar', 'البريد الإلكتروني أو كلمة المرور غير صحيحة.'),
(33, 'en', 'Incorrect email or password.'),
(35, 'ar', 'لم يتم التحقق من حسابك ، يرجى إلقاء نظرة على بريدك الإلكتروني'),
(35, 'en', 'Your account has not been verified, please take a look at your email');
