INSERT INTO `source_message` (`id`, `category`, `message`) VALUES
(1, 'app', 'login'),
(2, 'app', 'signup'),
(3, 'app', 'about'),
(4, 'app', 'logout'),
(5, 'app', 'contact'),
(6, 'app', 'username'),
(7, 'app', 'password'),
(8, 'app', 'remember me'),
(9, 'app', 'phone number'),
(10, 'app', 'forgot your password'),
(11, 'app', 'need new verification'),
(12, 'app', 'login facebook'),
(13, 'app', 'reset'),
(14, 'app', 'resend'),
(15, 'app', 'This username has already been taken.'),
(16, 'app', 'This email address has already been taken.'),
(17, 'app', 'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.'),
(18, 'app', 'submit'),
(19, 'app', 'name'),
(20, 'app', 'subject'),
(21, 'app', 'body'),
(22, 'app', 'email'),
(23, 'app', '{attribute} cannot be blank.'),
(24, 'yii', 'Yii Framework'),
(25, 'yii', 'Powered by {yii}'),
(26, 'yii', 'Login Required'),
(27, 'app', 'Email'),
(28, 'app', 'user.fields.username'),
(29, 'app', 'validation.required'),
(30, 'app', 'This phone number has already been taken.'),
(31, 'app', 'site.signup.phone_number_taken'),
(32, 'app', 'site.view.login_form_phone_error'),
(33, 'app', 'site.view.login_form_email_error'),
(34, 'app', 'site.email_not_verified'),
(35, 'app', 'site.email_not_verified'),
(36, 'app', 'not valid');